spring:
  application:
    name: neobank

app:
  telegram:
    id: id_бота
    chat-id: id_чата (Требование заказчика)
    username: наименование (Требование заказчика)
    token: токен бота
    chat-type: private
  backend:
    url: ссылка на backend NeoBank
    token-hash: sha256(token)
